---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: test-gitops    
  name: rollout-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rollout-demo
  name: rollout-demo
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rollout-demo
  project: default
  source:
    path: examples/canary
    repoURL: https://github.com/argoproj/rollouts-demo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
