= Red Hat Openshift GitOps Demo
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2021-10
// Metadata
:description: This document shows how to do a basic installation of ArgoCD customizing basic configuration of login.
:keywords: argocd, gitops, openshift, red hat
// Settings
:toc: 
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons
// Refs
:ocp-cluster-project: gitops



== Introduction

GitOps is an increasingly popular set of practices for managing the complexities of running hybrid multicluster Kubernetes infrastructure. GitOps centers on treating Git repositories as the single source of truth and applying Git workflows that have been consistently used for application development to infrastructure and application operators. 

This repository provides a starting point to deploy many different operator and applications, such as GitOps, ArgoCD, Nexus, as well as your first application.

== Installing ArgoCD and Openshift GitOps

https://docs.openshift.com/container-platform/4.8/cicd/gitops/gitops-release-notes.html[Red Hat OpenShift GitOps] Red Hat OpenShift GitOps uses https://argoproj.github.io/argo-cd/[Argo CD] to manage specific cluster-scoped resources, including platform operators, optional Operator Lifecycle Manager (OLM) operators, and user management. Argo CD is a popular Cloud Native Computing Foundation (CNCF) open source GitOps Kubernetes Operator for declarative configuration on Kubernetes clusters. 

Now, we are going to install the Red Hat OpenShift GitOps Operator to an OpenShift Container Platform cluster and logging in to the Argo CD instance.

[source, bash]
----
oc process -f templates/gitops-01-operator.yaml | oc apply -f -
----

After the installation is completed, the operator pods will be running in the `openshift-operators` project.

By default, the GitOps operator deploys an ArgoCD instance in the `openshift-gitops` project. To avoid that and have full control of the installation location, the https://access.redhat.com/solutions/6097231[following configuration] has been set in the previous OCP template.

[source, yaml]
----
    spec:
      config:
        env:
          - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
            value: "true"
----

Now, we are going to deploy our ArgoCD instance manually using the following template:

[source, bash]
----
oc process -f templates/gitops-02-argocd.yaml | oc apply -f -
----

This command will create a namespace `{ocp-cluster-project}`, a default Application Project and an ArgoCD cluster. The configuration used is the default Operator configuration with some small improvements: Delegating authentication on the OpenShift integrated login, or implementing basic RBAC policies.

Access the installed ArgoCD cluster using the following route:

[source, bash, subs="attributes"]
----
oc get routes argocd-cluster-server -n {ocp-cluster-project} --template="https://{{.spec.host}}"
----






=== Enabling the OpenShift integrated login

Enabling OpenShift integrated login is quite simple, but might not be perfectly documented as of today. It is already configured in the templates deployed in the section above. This is just for documentation purposes. 

This feature implies changes at several levels:

1. Set an environment variable at the operator level. This will tell the operator to enable Dex server for external authentication. https://github.com/redhat-developer/gitops-operator/issues/91#issuecomment-806660510[GH Issue], https://dev.to/camptocamp-ops/enable-openshift-login-on-argocd-from-gitops-2h9a[Blog post].
+
[source, yaml]
----
    spec:
      config:
        env:
          - name: DISABLE_DEX
            value: "false"
----

2. Configure the ArgoCD object to use the DEX Openshift login integration.
+
[source, yaml]
----
    spec:
      dex:
        openShiftOAuth: true
----

3. Configure the ArgoCD object with the desired RBAC policies. For example, the simples option:
+
[source, yaml]
----
    spec:
      rbac:
        defaultPolicy: 'role:readonly'
        policy: |
          g, system:cluster-admins, role:admin
        scopes: '[groups]'
----





[TIP]
====
After configuring Openshift login, you can still log in using a user / password. Use the user `admin` and obtain the password with the following command:
[source, bash, subs="attributes"]
----
oc extract secret/argocd-cluster-cluster -n {ocp-cluster-project}  --to=-
----
====




== Creating your first application





== Improving RBAC configuration





== Limiting the permissions of the Service Account













== Annex: Installing Nexus

[IMPORTANT]
====
TL;DR: Execute the following script to auto-install a Nexus instance in your cluster: `./auto-install.nexus.sh`
====

Nexus Repository OSS is an open source repository that supports many artifact formats, including Docker, Java™, and npm. With the Nexus tool integration, pipelines in your toolchain can publish and retrieve versioned apps and their dependencies by using central repositories that are accessible from other environments.

If you are planning to deploy your applications using Helm charts, most of the architectures you will need a Helm repository to host to packaged Helm charts. Install a Nexus repository manager using the following commands:


[source, bash]
----
# Define common variables
OPERATOR_NAMESPACE="nexus"

# Deploy operator
oc process -f templates/nexus-01-operator.yaml -p OPERATOR_NAMESPACE=$OPERATOR_NAMESPACE | oc apply -f -

# Workaround for issue: https://github.com/sonatype/operator-nxrm3/issues/8
oc adm policy add-scc-to-user privileged -z default -n $OPERATOR_NAMESPACE

# Deploy application instance
oc process -f templates/nexus-02-server.yaml -p OPERATOR_NAMESPACE=$OPERATOR_NAMESPACE -p SERVER_NAME="nexus-server" | oc apply -f -
----

=== Creating  a Helm repository

Create a Helm repository with the following steps:

* Access the Nexus route: `oc get routes nexus-server --template="https://{{.spec.host}}"`.
* Log in using the admin credentials: `admin` / `admin123`.
* Server Administration > Repositories > Create Repositories > "Helm(hosted)"
** name: `helm-charts`.
** DeploymentPolicy: `Allow redeploy`.
* Click on `Create repository`.

If you don't want to use the console, you can use CURL command to create this repository on the `auto-install-nexus` script.







== Openshift GitOps support and deployed versions

OpenShift GitOps is shipped inclusive as part of the OpenShift Container Platform subscription and supported per the Red Hat production terms of support.

Check the following table with GitOps versions and its equivalent to ArgoCD:

[%header,format=csv]
|===
GitOps version,OCP version,ArgoCD version, Release date
1.0 (TP), 4.6, 1.8, "Feb 12, 2021"
1.1, 4.7, X, "April 15, 2021"
1.2, 4.8, 2.0, "July 29, 2021"
1.3 (Not GA yet), 4.9, 2.1, "October, 2021?"
|===


For more information, check the https://access.redhat.com/support/policy/updates/openshift#gitops[Red Hat OpenShift Container Platform Life Cycle Policy].


Note that only the ArgoCD CRD is supported, the rest are Tech Preview in the latest version of Openshift GitOps:

[%header,format=csv]
|===
Feature, Support in GitOps 1.2
Argo CD, GA
Argo CD ApplicationSet, TP
Red Hat OpenShift GitOps Application Manager (kam), TP
Red Hat OpenShift GitOps Service, TP
|===

For more information check the Openshift GitOps https://docs.openshift.com/container-platform/4.8/cicd/gitops/gitops-release-notes.html#support-matrix-1-2_gitops-release-notes[release notes].



== Documentation and useful links

