---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-catalog
  namespace: {{ .Values.global.namespace }}
  labels:
    argocd.argoproj.io/project-inherit: global
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
