---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ .Values.global.namespace }}-{{ .Values.global.clusterName }}
spec:
  href: "https://{{ .Values.global.clusterName }}-server-{{ .Values.global.namespace }}.apps.{{ .Values.global.clusterDomain }}"
  location: ApplicationMenu
  text: ArgoCD
  applicationMenu:
    section: GitOps
    imageURL: https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/argo.png
