{{- if .Values.runOnInfra.enabled }}
---
apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  name: cluster
spec:
  # nodeSelector:
  #   node-role.kubernetes.io/infra: ""
  runOnInfra: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved
{{- end }}