---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  annotations:
    openshift.io/description: "This project contains all the resources related to the ArgoCD installation"
    openshift.io/display-name: "GitOps"
  labels:
    openshift.io/cluster-monitoring: "true"
