# Variable files for ArgoCD
global:
  namespace: openshift-gitops
  clusterName: argocd-cluster
  clusterDomain: $CLUSTER_DOMAIN

namespace:
  enabled: false

runOnInfra:
  enabled: false

argoRollout:
  enabled: false
  ha: false
