apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: gitops-operator
  annotations:
    description: Template to deploy a Red Hat Openshift GitOps operator on OCP.
    tags: argocd,gitops,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: gitops-operator
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic 
      name: openshift-gitops-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: openshift-gitops-operator.v1.2.1
      config:
        env:
          - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
            value: "true"
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "openshift-operators"