apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nexus-operator
  annotations:
    description: Template to deploy a Sonatype Nexus Repository Manager 3 operator on OCP.
    tags: nexus,sonatype,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: ${OPERATOR_NAMESPACE}
      annotations:
        openshift.io/description: "This project contains all the resources related to the operator for Nexus"
        openshift.io/display-name: "Nexus"
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: nexus
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      targetNamespaces:
        - ${OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: nxrm-operator-certified
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: nxrm-operator-certified
      source: certified-operators
      sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "nexus"