apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: gitops-argocd
  annotations:
    description: Template to deploy a Red Hat Openshift GitOps ArgoCd cluster on OCP.
    tags: argocd,gitops,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:

  - apiVersion: console.openshift.io/v1
    kind: ConsoleLink
    metadata:
      name: ${ARGOCD_NAMESPACE}-${ARGOCD_CLUSTER_NAME}
    spec:
      href: ${ARGOCD_ROUTE}
      location: ApplicationMenu
      text: ArgoCD
      applicationMenu:
        section: GitOps
        imageURL: https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/argo.png

parameters:
- name: ARGOCD_ROUTE
  description: "The project where the cluster will be installed."
  required: true
- name: ARGOCD_NAMESPACE
  description: "The project where the cluster will be installed."
  required: false
  value: "gitops"
- name: ARGOCD_CLUSTER_NAME
  description: "The name of the ArgoCD cluster."
  required: false
  value: "argocd-cluster"